appEnvironment: Development

serviceAccount:
  create: true

image:
  pullPolicy: Always

services:
  voyagerapi:
    create: true
    name: voyager-api
    gracefulShutdownConfig: true
    service:
      type: ClusterIP
      port: 80
    image:
      repository: rebbaprashanth/demo-app-relic
    resources:
      limits:
        memory: 900Mi
      requests:
        cpu: 80m
        memory: 700Mi
    env: VOYAGER_APP_ENVIRONMENT
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 300
