{{- range $k, $v := .Values.services }}
{{- if $v.create}}
{{- if $v.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $v.name }}
  labels:
    app.kubernetes.io/name: {{ $v.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  type: {{ $v.service.type }}
  ports:
    - port: {{ $v.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $v.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{- end }}
{{- end }}
{{- end }}
